<?php
/**
 * @file
 * Provides support for Open Graph Protocol meta tags.
 */

/**
 * Implements hook_preprocess_page().
 */
function metatag_opengraph_preprocess_page(&$variables) {
  // @TODO Would it be worth dynamically identifying whether these should be
  // added, or just output them all?

  if (!isset($variables['rdf_namespaces'])) {
    $variables['rdf_namespaces'] = '';
  }

  // Need an extra namespace for the 'og' tags.
  $variables['rdf_namespaces'] .= "\n  xmlns:og=\"http://ogp.me/ns#\"";
  // Need an extra namespace for the "article" tags.
  $variables['rdf_namespaces'] .= "\n  xmlns:article=\"http://ogp.me/ns/article#\"";
  // Need an extra namespace for the "book" tags.
  $variables['rdf_namespaces'] .= "\n  xmlns:book=\"http://ogp.me/ns/book#\"";
  // Need an extra namespace for the "profile" tags.
  $variables['rdf_namespaces'] .= "\n  xmlns:profile=\"http://ogp.me/ns/profile#\"";
  // Need an extra namespace for the "video" tags.
  $variables['rdf_namespaces'] .= "\n  xmlns:video=\"http://ogp.me/ns/video#\"";
  // And for product tags.
  $variables['rdf_namespaces'] .= "\n  xmlns:product=\"http://ogp.me/ns/product#\"";
}
