<?php
/**
 * @file
 * Primary hook implementations for Metatag:Google CSE.
 */

/**
 * Implements hook_theme().
 */
function metatag_google_cse_theme($existing, $type, $theme, $path) {
  $info['metatag_google_cse'] = array(
    'render element' => 'element',
  );

  return $info;
}

/**
 * Theme callback for a normal meta tag.
 *
 * The format is:
 * <meta name="[name]" content="[value]" />
 */
function theme_metatag_google_cse($variables) {
  $variables['#tag'] = 'meta';
  $element = &$variables['element'];

  if ($element['#name'] === 'google_rating') {
    $element['#name'] = 'rating';
  }

  $args = array(
    '#name'  => 'name',
    '#value' => 'content',
  );
  element_set_attributes($element, $args);
  unset($element['#value']);
  return theme('head_tag', $variables);
}
